# Generated by Django 2.2.7 on 2019-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20191106_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
